server:
  port: 8081

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB


ipfs:
  node:
    host: ${IPFS_HOST:localhost}
    port: ${IPFS_PORT:5001}
    address: /ip4/127.0.0.1/tcp/5001

  cluster:
    host: ${IPFS_CLUSTER_HOST:localhost}
    port: ${IPFS_CLUSTER_PORT:9094}



