
@startuml

title __High-Level read document sequence__

actor user
box "Olam Node" #LightBlue
participant "Olam backend" as ob
database "Ethereum Private" as ep
database "IPFS" as ip #99FF99
end box

user -> ob : read document request
ob -> ep : verify permission request
ep --> ob : verify permission response
ob -> ob : encrypt document symmetric key
ob -> ip : get document request
ip -> ob : get document response
ob --> user : read document response (document + key)

@enduml




