
@startuml

title __High-Level submit document sequence__

actor user
box "Olam Node" #LightBlue
participant "Olam backend"
database "Ethereum Private"
database "IPFS" #99FF99
end box

user -> "Olam backend" : submit document request
"Olam backend" -> "Ethereum Private" : verify permission request
"Ethereum Private" --> "Olam backend" : verify permission response
"Olam backend" -> "Olam backend" : encrypt document
"Olam backend" -> "IPFS" : save document request
"IPFS" -> "Olam backend" : save document response
"Olam backend" -> "Ethereum Private" : save document hash + encrypted symmetric key
"Ethereum Private" --> "Olam backend" : save document hash response
"Olam backend" --> user : submit document response

@enduml




